/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "SS2012FPGA.h"

static void *
get_skel_small_jp_ac_utsunomiya_is_SS2012FPGA
   (POA_jp_ac_utsunomiya_is_SS2012FPGA * servant, const char *opname,
    void **m_data, void **impl)
{
   switch (opname[0]) {
     case 'g':
	if (strcmp((opname + 1), "etAlarmSwitchState"))
	   break;
	*impl =
	   (void *) servant->vepv->jp_ac_utsunomiya_is_SS2012FPGA_epv->
	   getAlarmSwitchState;
	*m_data = &jp_ac_utsunomiya_is_SS2012FPGA__imp.methods[2];
	return (void *)
	   _RtORB_impl_jp_ac_utsunomiya_is_SS2012FPGA_getAlarmSwitchState;
	break;
     case 'p':
	if (strcmp((opname + 1), "layAlarmSound"))
	   break;
	*impl =
	   (void *) servant->vepv->jp_ac_utsunomiya_is_SS2012FPGA_epv->
	   playAlarmSound;
	*m_data = &jp_ac_utsunomiya_is_SS2012FPGA__imp.methods[1];
	return (void *)
	   _RtORB_impl_jp_ac_utsunomiya_is_SS2012FPGA_playAlarmSound;
	break;
     case 'r':
	if (strcmp((opname + 1), "eceiveIrDAdata"))
	   break;
	*impl =
	   (void *) servant->vepv->jp_ac_utsunomiya_is_SS2012FPGA_epv->
	   receiveIrDAdata;
	*m_data = &jp_ac_utsunomiya_is_SS2012FPGA__imp.methods[4];
	return (void *)
	   _RtORB_impl_jp_ac_utsunomiya_is_SS2012FPGA_receiveIrDAdata;
	break;
     case 's':
	switch (opname[1]) {
	  case 'e':
	     switch (opname[2]) {
	       case 'n':
		  if (strcmp((opname + 3), "dIrDAdata"))
		     break;
		  *impl =
		     (void *) servant->vepv->
		     jp_ac_utsunomiya_is_SS2012FPGA_epv->sendIrDAdata;
		  *m_data = &jp_ac_utsunomiya_is_SS2012FPGA__imp.methods[3];
		  return (void *)
		     _RtORB_impl_jp_ac_utsunomiya_is_SS2012FPGA_sendIrDAdata;
		  break;
	       case 't':
		  if (strcmp((opname + 3), "MotorTorque"))
		     break;
		  *impl =
		     (void *) servant->vepv->
		     jp_ac_utsunomiya_is_SS2012FPGA_epv->setMotorTorque;
		  *m_data = &jp_ac_utsunomiya_is_SS2012FPGA__imp.methods[0];
		  return (void *)
		     _RtORB_impl_jp_ac_utsunomiya_is_SS2012FPGA_setMotorTorque;
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     default:
	break;
   }
   return NULL;
}

void
POA_jp_ac_utsunomiya_is_SS2012FPGA__init(PortableServer_Servant servant,
					 CORBA_Environment * env)
{
   static PortableServer_ClassInfo class_info =
      { NULL, (void *(*)()) &get_skel_small_jp_ac_utsunomiya_is_SS2012FPGA,
"IDL:jp/ac/utsunomiya/is/SS2012FPGA:1.0", &jp_ac_utsunomiya_is_SS2012FPGA__classid,
&jp_ac_utsunomiya_is_SS2012FPGA__imp };
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   RtORB_POA_Object__create(&class_info, servant, NULL, NULL);
}

void
POA_jp_ac_utsunomiya_is_SS2012FPGA__fini(PortableServer_Servant servant,
					 CORBA_Environment * env)
{
   PortableServer_ServantBase__fini(servant, env);
}
